package com.purpl.prog6;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JFileChooser;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.HashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicInteger;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author izada
 * 
 * 
 *
 */
public class JFrameGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameGUI.class.getName());
    
    private final ArrayList<Integration.ResIntegral> entries = new ArrayList<>();
    private DefaultTableModel tableModel;
    private boolean isCleared = false;
    private volatile boolean calcInProgress = false;
    private static final int THREAD_COUNT = 9;

    private ClientUdpService udpService;
    private final AtomicInteger requestCounter = new AtomicInteger(1000);
    private final HashMap<Integer, Integer> requestRows = new HashMap<>();

    // TODO: поменяй на IP Ubuntu Server, например "192.168.1.20".
    private static final String SERVER_HOST = "127.0.0.1";
    private static final int SERVER_PORT = 5000;

    /**
     * Creates new form JFrameGUI
     */
    public JFrameGUI() {
        initComponents();
        
        tableModel = new DefaultTableModel(
                new Object[]{"Нижняя граница", "Верхняя граница", "Шаг", "Результат"}, 0) {
            @Override public boolean isCellEditable(int row, int col) { 
                if (col == 3) {
                    return false;
                } else {
                    return true;
                }
                
            }
        };
        jTableVariables.setModel(tableModel);

        initUdpClient();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (udpService != null) {
                    udpService.stop();
                }
            }
        });
    }

    private void initUdpClient() {
        try {
            udpService = new ClientUdpService(this, SERVER_HOST, SERVER_PORT);
            udpService.start();
            udpService.registerOnServer();

            JOptionPane.showMessageDialog(this,
                    "UDP-клиент запущен на порту: " + udpService.getLocalPort(),
                    "Сеть", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Ошибка запуска UDP-клиента: " + ex.getMessage(),
                    "Сеть", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jTextFieldUpperLimit = new javax.swing.JTextField();
        jTextFieldStep = new javax.swing.JTextField();
        jTextFieldLowerLimit = new javax.swing.JTextField();
        jLabelLowerLimit = new javax.swing.JLabel();
        jLabelUpperLimit = new javax.swing.JLabel();
        jLabelStep = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVariables = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCalc = new javax.swing.JButton();
        jLabelMainHeader = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jButtonFill = new javax.swing.JButton();
        jButtonWrite = new javax.swing.JButton();
        jButtonWriteSer = new javax.swing.JButton();
        jButtonRead = new javax.swing.JButton();
        jButtonReadSer = new javax.swing.JButton();
        jLabelLowerLimit1 = new javax.swing.JLabel();
        jLabelLowerLimit2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelLowerLimit.setText("Нижняя граница интегрирования:");

        jLabelUpperLimit.setText("Верхняя граница интегрирования:");

        jLabelStep.setText("Шаг интегрирования:");

        jTableVariables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Нижняя граница", "Верхняя граница", "Шаг", "Результат"
            }
        ));
        jScrollPane2.setViewportView(jTableVariables);

        jButtonAdd.setBackground(new java.awt.Color(255, 51, 204));
        jButtonAdd.setText("Добавить");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jButtonDelete.setBackground(new java.awt.Color(255, 51, 204));
        jButtonDelete.setText("Удалить");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonCalc.setBackground(new java.awt.Color(255, 51, 204));
        jButtonCalc.setText("Вычислить");
        jButtonCalc.addActionListener(this::jButtonCalcActionPerformed);

        jLabelMainHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelMainHeader.setText("Функция: cos(x^2)");

        jButtonClear.setBackground(new java.awt.Color(102, 255, 51));
        jButtonClear.setText("Очистить");
        jButtonClear.addActionListener(this::jButtonClearActionPerformed);

        jButtonFill.setBackground(new java.awt.Color(102, 255, 51));
        jButtonFill.setText("Заполнить");
        jButtonFill.addActionListener(this::jButtonFillActionPerformed);

        jButtonWrite.setBackground(new java.awt.Color(0, 204, 204));
        jButtonWrite.setText("Write");
        jButtonWrite.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.orange, java.awt.Color.orange, null));
        jButtonWrite.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonWrite.addActionListener(this::jButtonWriteActionPerformed);

        jButtonWriteSer.setBackground(new java.awt.Color(0, 204, 204));
        jButtonWriteSer.setText("WriteSer");
        jButtonWriteSer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.orange, java.awt.Color.orange, null));
        jButtonWriteSer.addActionListener(this::jButtonWriteSerActionPerformed);

        jButtonRead.setBackground(new java.awt.Color(0, 204, 204));
        jButtonRead.setText("Read");
        jButtonRead.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.orange, java.awt.Color.orange, null));
        jButtonRead.addActionListener(this::jButtonReadActionPerformed);

        jButtonReadSer.setBackground(new java.awt.Color(0, 204, 204));
        jButtonReadSer.setText("ReadSer");
        jButtonReadSer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.orange, java.awt.Color.orange, null));
        jButtonReadSer.addActionListener(this::jButtonReadSerActionPerformed);

        jLabelLowerLimit1.setText("Сериализация");

        jLabelLowerLimit2.setText("Нормальный");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Запись в файл");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Добавление элемента");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Таблица элементов");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLowerLimit)
                            .addComponent(jLabelUpperLimit)
                            .addComponent(jLabelStep))
                        .addGap(6, 6, 6)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUpperLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLowerLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStep, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonRead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelLowerLimit2)
                                    .addComponent(jButtonWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelLowerLimit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonWriteSer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonReadSer, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(29, 29, 29)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFill, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(159, 159, 159))))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(207, 207, 207))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMainHeader)
                .addGap(368, 368, 368))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelMainHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFill, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLowerLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLowerLimit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUpperLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUpperLimit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStep, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStep))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLowerLimit1)
                            .addComponent(jLabelLowerLimit2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonWriteSer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRead, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReadSer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if(isCleared == true)
        {
            try
            {
                entries.clear();
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this,
                "Ошибка: " + ex.getMessage(),
                "Удаление данных", JOptionPane.WARNING_MESSAGE);
            }
            isCleared = false;
        }
        
        try {
            double a = parse(jTextFieldLowerLimit.getText(), "Нижняя граница");
            double b = parse(jTextFieldUpperLimit.getText(), "Верхняя граница");
            double h = parse(jTextFieldStep.getText(), "Шаг");

            if (h <= 0) throw new IllegalArgumentException("Шаг должен быть > 0.");

            Integration.ResIntegral e = new Integration.ResIntegral(a, b, h);
            entries.add(e);

            tableModel.addRow(new Object[]{a, b, h, ""});

            jTextFieldLowerLimit.setText("");
            jTextFieldUpperLimit.setText("");
            jTextFieldStep.setText("");

            int last = tableModel.getRowCount() - 1;
            jTableVariables.setRowSelectionInterval(last, last);

        } catch (OutOfLimitException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Ошибка", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Ошибка: " + ex.getMessage(),
                "Ввод данных", JOptionPane.WARNING_MESSAGE);
        }                                          
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
                int row = jTableVariables.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Выбери строку в таблице.",
                    "Удаление", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        entries.remove(row);
        tableModel.removeRow(row);
    }//GEN-LAST:event_jButtonDeleteActionPerformed
    
    private class IntegralCalcTask implements Runnable {
        private final double a;
        private final double b;
        private final double h;
        private final int row;
        private final int num;

        public IntegralCalcTask(double a, double b, double h, int row, int num) {
            this.a = a;
            this.b = b;
            this.h = h;
            this.row = row;
            this.num = num;
        }

        @Override
        public void run() {
            try {
                System.out.println("Thread " + num);
                Integration.ResIntegral e = new Integration.ResIntegral(a, b, h);
                double res = Integration.integrateSin(e.getA(), e.getB(), e.getH());
                e.setRes(res);

                javax.swing.SwingUtilities.invokeLater(() -> {
                    tableModel.setValueAt(res, row, 3);
                    if (row < entries.size()) {
                        entries.set(row, e);
                    }
                });
            } catch (OutOfLimitException ex) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(JFrameGUI.this,
                            ex.getMessage(),
                            "Ошибка", JOptionPane.WARNING_MESSAGE);
                });
            } catch (Exception ex) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(JFrameGUI.this,
                            "Ошибка вычисления: " + ex.getMessage(),
                            "Ошибка", JOptionPane.WARNING_MESSAGE);
                });
            }
        }
    }
    
    private void jButtonCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcActionPerformed
        int row = jTableVariables.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Выбери строку в таблице.",
                    "Вычисление", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (udpService == null) {
            JOptionPane.showMessageDialog(this,
                    "UDP-клиент не запущен.",
                    "Сеть", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double A = parse(tableModel.getValueAt(row, 0).toString(), "Нижняя граница");
            double B = parse(tableModel.getValueAt(row, 1).toString(), "Верхняя граница");
            double H = parse(tableModel.getValueAt(row, 2).toString(), "Шаг");

            int requestId = requestCounter.incrementAndGet();
            requestRows.put(requestId, row);

            tableModel.setValueAt("ожидание...", row, 3);

            udpService.sendCalcRequest(requestId, A, B, H);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Ошибка отправки запроса: " + ex.getMessage(),
                    "Ошибка", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCalcActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        for (int i = tableModel.getRowCount() - 1; i >= 0; i--) 
        {
            tableModel.removeRow(i);
        }
        jTableVariables.clearSelection();
        isCleared = true;
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFillActionPerformed
        tableModel.setRowCount(0);
        
        for (Integration.ResIntegral e : entries) {
            Object res = (e.getRes() == null) ? "" : e.getRes();
            tableModel.addRow(new Object[]{ e.getA(), e.getB(), e.getH(), res });
        }
        isCleared = false;
    }//GEN-LAST:event_jButtonFillActionPerformed

    private void jButtonWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteActionPerformed
        if(isCleared == true)
        {
            try
            {
                entries.clear();
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this,
                "Ошибка: " + ex.getMessage(),
                "Удаление данных", JOptionPane.WARNING_MESSAGE);
            }
            isCleared = false;
        }
        
        if(!entries.isEmpty())
        {
            try 
            {
                File file = chooseFile(true, "Сохранить файл", "txt", "Текстовые файлы (*.txt)");
                if (file == null) return;
                
                
                writeFile(file, entries);
                JOptionPane.showMessageDialog(this, "Файл сохранён:\n" + file.getAbsolutePath(),
                        "Запись", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this,
                        "Ошибка записи: " + ex.getMessage());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,
                        "Ошибка записи: лист entries пуст");
        }
    }//GEN-LAST:event_jButtonWriteActionPerformed

    private void jButtonWriteSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteSerActionPerformed
        if(isCleared == true)
        {
            try
            {
                entries.clear();
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(this,
                "Ошибка: " + ex.getMessage(),
                "Удаление данных", JOptionPane.WARNING_MESSAGE);
            }
            isCleared = false;
        }
        
        if(!entries.isEmpty())
        {
            try 
            {
                File file = chooseFile(true, "Сохранить файл", "txt", "Текстовые файлы (*.txt)");
                if (file == null) return;
                
                
                writeSer(file, entries);
                JOptionPane.showMessageDialog(this, "Файл сохранён:\n" + file.getAbsolutePath(),
                        "Запись", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this,
                        "Ошибка записи: " + ex.getMessage());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,
                        "Ошибка записи: лист entries пуст");
        }
    }//GEN-LAST:event_jButtonWriteSerActionPerformed

    private void jButtonReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadActionPerformed
        entries.clear();
        File file = chooseFile(false, "Открыть файл", "txt", "Текстовые файлы (*.txt)");
        if (file == null) return;
        
        try {
            var list = readFile(file);
            loadEntriesToTable(list);
            JOptionPane.showMessageDialog(this, "Прочитано:\n" + file.getAbsolutePath());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ошибка чтения: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonReadActionPerformed

    private void jButtonReadSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadSerActionPerformed
        entries.clear();
        File file = chooseFile(false, "Открыть файл", "txt", "Текстовые файлы (*.txt)");
        if (file == null) return;
        
        try {
            var list = readSer(file);
            loadEntriesToTable(list);
            JOptionPane.showMessageDialog(this, "Прочитано:\n" + file.getAbsolutePath());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ошибка чтения: " + ex.getMessage());
        }
    }                                              

    private double parse(String s, String fieldName) {
        s = s.trim();
        if (s.isEmpty()) throw new IllegalArgumentException(fieldName + " не задано.");
        s = s.replace(',', '.');
        return Double.parseDouble(s);
    }//GEN-LAST:event_jButtonReadSerActionPerformed

    private void writeFile(File file, ArrayList<Integration.ResIntegral> list)
    {
        BufferedWriter bw = null;
        try 
        {
            bw = new BufferedWriter(new FileWriter(file, StandardCharsets.UTF_8));
            bw.write("{");
            bw.newLine();
            int count = 0;
            for(Integration.ResIntegral e : list)
            {
                String a = String.format(Locale.US, "%.10f", e.getA());
                String b = String.format(Locale.US, "%.10f", e.getB());
                String h = String.format(Locale.US, "%.10f", e.getH());
                String res;
                if(e.getRes() != null)
                {
                    res = String.format(Locale.US, "%.10f", e.getRes());
                }
                else
                {
                    res = "n";
                }
                bw.write("\"" + count + "\" : {" + "\"a\":" + a + "," + "\"b\":" + b + "," + "\"h\":" + h + "," + "\"res\":" + res + "},");
                count++;
                bw.newLine();
            }
            bw.write("}");
            bw.flush();
            bw.close();
        }
        catch (IOException ex) 
        { 
            ex.printStackTrace(); 
        }
    }
    
    private ArrayList<Integration.ResIntegral> readFile(File file)
    {
        ArrayList<Integration.ResIntegral> list = new ArrayList<>();
        BufferedReader br = null;
        try
        {
            br = new BufferedReader(new FileReader(file, StandardCharsets.UTF_8));
            String line;
            line = br.readLine();
            int i = 0;
            while(!(line = br.readLine()).equals("}"))
            {
                i++;
                String[] p = line.split(" : ");
                
                String cou = p[0];
                String znach = p[1];
                
                znach = znach.replace("{","");
                znach = znach.replace("},","");
                
                String[] pp = znach.split(",");
                
                String aa = pp[0];
                String bb = pp[1];
                String hh = pp[2];
                String resres = pp[3];
                
                String[] A = aa.split(":");
                String[] B = bb.split(":");
                String[] H = hh.split(":");
                String[] RES = resres.split(":");
                
                double a = parse(A[1], "Нижняя граница");
                double b = parse(B[1], "Верхняя граница");
                double h = parse(H[1], "Шаг");
                
                Integration.ResIntegral e = new Integration.ResIntegral(a, b, h);
                
                if (!RES[1].equals("\"n\"")){
                    String resStr = RES[1].trim();
                    resStr = resStr.replace(',', '.');
                    e.setRes(Double.parseDouble(resStr));
                }
                list.add(e);
                
            }
        }
        catch(IOException ex)
        {
            ex.printStackTrace();
        }
        catch(OutOfLimitException e)
        {
            e.printStackTrace();
        }
        return list;
    }

    private void writeSer(File file, ArrayList<Integration.ResIntegral> list)
    {
        ObjectOutputStream out = null;
        
        try
        {
            out = new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream(file)));
            out.writeObject(list);
            out.close();
        }
        catch(IOException ex)
        {
            ex.printStackTrace();
        }
    }
    
    private ArrayList<Integration.ResIntegral> readSer(File file)
    {
        ObjectInputStream in = null;
        ArrayList<Integration.ResIntegral> obj = null;
        try
        {
            in = new ObjectInputStream(new BufferedInputStream(new FileInputStream(file)));
            obj = (ArrayList<Integration.ResIntegral>)in.readObject();
            in.close();
            return (ArrayList<Integration.ResIntegral>) obj;
        }
        catch(IOException ex)
        {
            ex.printStackTrace();
        }
        catch(ClassNotFoundException e)
        {
            e.printStackTrace();
        }
        return new ArrayList<>();
    }
    
    private void loadEntriesToTable(ArrayList<Integration.ResIntegral> list) 
    {
        entries.clear();
        entries.addAll(list);

        tableModel.setRowCount(0);
        for (Integration.ResIntegral e : entries) 
        {
            Object res = (e.getRes() == null) ? "" : e.getRes();
            tableModel.addRow(new Object[]{e.getA(), e.getB(), e.getH(), res});
        }

        isCleared = false;
        jTableVariables.clearSelection();
    }
    
    private File chooseFile(boolean save, String title, String extension, String description) 
    {
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle(title);
        fc.setFileFilter(new FileNameExtensionFilter(description, extension));

        int res = save ? fc.showSaveDialog(this) : fc.showOpenDialog(this);
        if (res != JFileChooser.APPROVE_OPTION) return null;

        File f = fc.getSelectedFile();

        return f;
    }


    public void receiveFinalResult(int requestId, double result) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            Integer row = requestRows.get(requestId);

            if (row == null) {
                JOptionPane.showMessageDialog(this,
                        "Получен результат для неизвестного запроса: " + requestId,
                        "Сеть", JOptionPane.WARNING_MESSAGE);
                return;
            }

            tableModel.setValueAt(result, row, 3);

            try {
                double a = parse(tableModel.getValueAt(row, 0).toString(), "Нижняя граница");
                double b = parse(tableModel.getValueAt(row, 1).toString(), "Верхняя граница");
                double h = parse(tableModel.getValueAt(row, 2).toString(), "Шаг");

                Integration.ResIntegral e = new Integration.ResIntegral(a, b, h);
                e.setRes(result);

                if (row < entries.size()) {
                    entries.set(row, e);
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        "Результат получен, но не удалось обновить коллекцию: " + ex.getMessage(),
                        "Сеть", JOptionPane.WARNING_MESSAGE);
            }

            requestRows.remove(requestId);
        });
    }

    public void calculateServerTask(Message msg) {
        new Thread(() -> {
            try {
                double result = calculatePartInThreads(msg.getA(), msg.getB(), msg.getH());

                udpService.sendCalcResult(
                        msg.getRequestId(),
                        msg.getPartNum(),
                        result
                );

            } catch (Exception ex) {
                showNetworkError("Ошибка вычисления части интеграла: " + ex.getMessage());
            }
        }).start();
    }

    private double calculatePartInThreads(double a, double b, double h) throws Exception {
    double[] results = new double[THREAD_COUNT];
    CountDownLatch latch = new CountDownLatch(THREAD_COUNT);

    for (int i = 0; i < THREAD_COUNT; i++) {
        final int index = i;

        Thread t = new Thread(() -> {
            try {
                System.out.println("Client thread " + index);

                Integration.ResIntegral e = new Integration.ResIntegral(a, b, h);
                double res = Integration.integrateSin(e.getA(), e.getB(), e.getH());

                results[index] = res;

                System.out.println("Client thread " + index
                        + " calculated full part ["
                        + a + "; " + b + "] = " + res);

            } catch (Exception ex) {
                System.out.println("Client thread " + index
                        + " error: " + ex.getMessage());
            } finally {
                latch.countDown();
            }
        });

        t.start();
    }

    latch.await();

    return results[0];
}

    public void showNetworkError(String text) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            JOptionPane.showMessageDialog(this,
                    text,
                    "Сетевая ошибка", JOptionPane.WARNING_MESSAGE);
        });
    }

    public void showNetworkStatus(String text) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            System.out.println(text);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCalc;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFill;
    private javax.swing.JButton jButtonRead;
    private javax.swing.JButton jButtonReadSer;
    private javax.swing.JButton jButtonWrite;
    private javax.swing.JButton jButtonWriteSer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLowerLimit;
    private javax.swing.JLabel jLabelLowerLimit1;
    private javax.swing.JLabel jLabelLowerLimit2;
    private javax.swing.JLabel jLabelMainHeader;
    private javax.swing.JLabel jLabelStep;
    private javax.swing.JLabel jLabelUpperLimit;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableVariables;
    private javax.swing.JTextField jTextFieldLowerLimit;
    private javax.swing.JTextField jTextFieldStep;
    private javax.swing.JTextField jTextFieldUpperLimit;
    // End of variables declaration//GEN-END:variables
}
